In [36]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("/content/drive/MyDrive/musterigetirisihesaplama/persona.csv")

In [3]:
df.head(10)

   PRICE   SOURCE   SEX COUNTRY  AGE
0     39  android  male     bra   17
1     39  android  male     bra   17
2     49  android  male     bra   17
3     29  android  male     tur   17
4     49  android  male     tur   17
5     29  android  male     bra   17
6     19  android  male     bra   17
7     59  android  male     bra   17
8     49  android  male     bra   17
9     19  android  male     bra   17

In [7]:
df.shape

(5000, 5)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   PRICE    5000 non-null   int64
 1   SOURCE   5000 non-null   object
 2   SEX      5000 non-null   object
 3   COUNTRY  5000 non-null   object
 4   AGE      5000 non-null   int64
dtypes: int64(2), object(3)
memory usage: 234.4+ KB

In [16]:
# Kaç unique source vardır?
print("Unique source değerleri: ",df['SOURCE'].nunique())
# Frekansları nedir?
print("Frekansları:\n",df['SOURCE'].value_counts())

Unique source değerleri:  2
Frekansları:
 android    2974
ios        2026
Name: SOURCE, dtype: int64

In [17]:
# Kaç unique price vardır?
print("Unique: ", df["PRICE"].unique())
print("Nunique: ", df["PRICE"].nunique())

Unique:  [39 49 29 19 59  9]
Nunique:  6

In [18]:
# Hangi PRICE'dan kaçar tane satış gerçekleşmiş?
df["PRICE"].value_counts()

29    1305
39    1260
49    1031
19     992
59     212
9      200
Name: PRICE, dtype: int64

In [19]:
# Hangi ülkeden kaçar tane satış olmuş?
df["COUNTRY"].value_counts()

usa    2065
bra    1496
deu     455
tur     451
fra     303
can     230
Name: COUNTRY, dtype: int64

In [23]:
# Ülkelere göre satışlardan toplam ne kadar kazanılmış?
df.groupby("COUNTRY")["PRICE"].sum()

COUNTRY
bra    51354
can     7730
deu    15485
fra    10177
tur    15689
usa    70225
Name: PRICE, dtype: int64

In [26]:
# SOURCE türlerine göre satış sayıları nedir?
df["SOURCE"].value_counts()

android    2974
ios        2026
Name: SOURCE, dtype: int64

In [27]:
# Ülkelere göre PRICE ortalamaları nedir?
df.groupby("COUNTRY")["PRICE"].mean()

COUNTRY
bra    34.327540
can    33.608696
deu    34.032967
fra    33.587459
tur    34.787140
usa    34.007264
Name: PRICE, dtype: float64

In [28]:
# SOURCE'lara göre PRICE ortalamaları nedir?
df.groupby("SOURCE")["PRICE"].mean()

SOURCE
android    34.174849
ios        34.069102
Name: PRICE, dtype: float64

In [29]:
# COUNTRY-SOURCE kırılımında PRICE ortalamaları nedir?
df.groupby(["COUNTRY","SOURCE"])["PRICE"].mean()

COUNTRY  SOURCE
bra      android    34.387029
         ios        34.222222
can      android    33.330709
         ios        33.951456
deu      android    33.869888
         ios        34.268817
fra      android    34.312500
         ios        32.776224
tur      android    36.229437
         ios        33.272727
usa      android    33.760357
         ios        34.371703
Name: PRICE, dtype: float64

In [30]:
# COUNTRY, SOURCE, SEX, AGE kırılımında ortalama kazançlar nedir?
df.groupby(["COUNTRY","SOURCE","SEX","AGE"])["PRICE"].mean()

COUNTRY  SOURCE   SEX     AGE
bra      android  female  15     38.714286
                          16     35.944444
                          17     35.666667
                          18     32.255814
                          19     35.206897
                                   ...
usa      ios      male    42     30.250000
                          50     39.000000
                          53     34.000000
                          55     29.000000
                          59     46.500000
Name: PRICE, Length: 348, dtype: float64

In [33]:
# Önceki sorudaki çıktıyı daha iyi görebilmek için sort_values metodunu azalan olacak şekilde PRICE’a göre uygulayınız.
# Çıktıyı agg_df olarak kaydediniz.

agg_df = df.groupby(["COUNTRY","SOURCE","SEX","AGE"])["PRICE"].mean().sort_values(ascending=False)
agg_df.head(10)

COUNTRY  SOURCE   SEX     AGE
bra      android  male    46     59.0
usa      android  male    36     59.0
fra      android  female  24     59.0
usa      ios      male    32     54.0
deu      android  female  36     49.0
                          51     49.0
         ios      male    20     49.0
usa      android  female  47     49.0
fra      ios      male    20     49.0
usa      ios      male    59     46.5
Name: PRICE, dtype: float64

In [35]:
# Indekste yer alan isimleri değişken ismine çeviriniz.
agg_df = agg_df.reset_index()
agg_df.head(10)

  COUNTRY   SOURCE     SEX  AGE  PRICE
0     bra  android    male   46   59.0
1     usa  android    male   36   59.0
2     fra  android  female   24   59.0
3     usa      ios    male   32   54.0
4     deu  android  female   36   49.0
5     deu  android  female   51   49.0
6     deu      ios    male   20   49.0
7     usa  android  female   47   49.0
8     fra      ios    male   20   49.0
9     usa      ios    male   59   46.5

In [42]:
# Age değişkenini kategorik değişkene çeviriniz ve agg_df’e ekleyiniz.
# Aralıkları ikna edici şekilde oluşturunuz.
# Örneğin: ‘0_18', ‘19_23', '24_30', '31_40', '41_70'

bins = [0, 18, 23, 30, 40, agg_df["AGE"].max()]
labels = ['0_18', "19_23", '24_30', '31_40', '41_' +str(agg_df["AGE"].max())]
agg_df["age_cat"] = pd.cut(agg_df["AGE"],bins = bins, labels = labels, duplicates= 'raise', right=True, include_lowest = False)
agg_df.head(10)

  COUNTRY   SOURCE     SEX  AGE  PRICE age_cat
0     bra  android    male   46   59.0   41_66
1     usa  android    male   36   59.0   31_40
2     fra  android  female   24   59.0   24_30
3     usa      ios    male   32   54.0   31_40
4     deu  android  female   36   49.0   31_40
5     deu  android  female   51   49.0   41_66
6     deu      ios    male   20   49.0   19_23
7     usa  android  female   47   49.0   41_66
8     fra      ios    male   20   49.0   19_23
9     usa      ios    male   59   46.5   41_66

In [47]:
# Yeni seviye tabanlı müşterileri (persona) tanımlayınız ve veri setine değişken olarak ekleyiniz.
# Yeni eklenecek değişkenin adı: customers_level_based
# Önceki soruda elde edeceğiniz çıktıdaki gözlemleri bir araya getirerek customers_level_based değişkenini oluşturmanız gerekmektedir.

agg_df["customers_level_based"] = agg_df[["COUNTRY","SOURCE","SEX","age_cat"]].agg(lambda x: '_'.join(x),axis=1)
agg_df.head(10)

,COUNTRY,SOURCE,SEX,AGE,PRICE,age_cat,customers_level_based,SEGMENT
0,bra,android,male,46,59.0,41_66,bra_android_male_41_66,A
1,usa,android,male,36,59.0,31_40,usa_android_male_31_40,A
2,fra,android,female,24,59.0,24_30,fra_android_female_24_30,A
3,usa,ios,male,32,54.0,31_40,usa_ios_male_31_40,A
4,deu,android,female,36,49.0,31_40,deu_android_female_31_40,A
5,deu,android,female,51,49.0,41_66,deu_android_female_41_66,A
6,deu,ios,male,20,49.0,19_23,deu_ios_male_19_23,A
7,usa,android,female,47,49.0,41_66,usa_android_female_41_66,A
8,fra,ios,male,20,49.0,19_23,fra_ios_male_19_23,A
9,usa,ios,male,59,46.5,41_66,usa_ios_male_41_66,A

In [45]:
# Yeni müşterileri (Örnek: USA_ANDROID_MALE_0_18) PRICE’a göre 4 segmente ayırınız.
# Segmentleri SEGMENT isimlendirmesi ile değişken olarak agg_df’e ekleyiniz.
agg_df["SEGMENT"] = pd.qcut(agg_df["PRICE"], 4, labels = ["D","C","B","A"])
# Segmentleri betimleyiniz (Segmentlere göre group by yapıp price mean, max, sum’larını alınız)
agg_df.groupby("SEGMENT").agg({"PRICE": ["mean", "max","sum"]})

             PRICE
              mean        max          sum
SEGMENT
D        27.302596  31.105263  2375.325850
C        32.933339  34.000000  3128.667165
B        35.436170  37.000000  2870.329792
A        41.434736  59.000000  3521.952577

In [49]:
# 33 yaşında ANDROID kullanan bir Türk kadını hangi segmente aittir ve ortalama ne kadar gelir kazandırması beklenir?
new_user = "tur_android_female_31_40"
agg_df[agg_df["customers_level_based"] == new_user]

,COUNTRY,SOURCE,SEX,AGE,PRICE,age_cat,customers_level_based,SEGMENT
18,tur,android,female,32,43.000000,31_40,tur_android_female_31_40,A
35,tur,android,female,31,40.666667,31_40,tur_android_female_31_40,A

In [50]:
# 35 yaşında IOS kullanan bir Fransız kadını hangi segmente aittir ve ortalama ne kadar gelir kazandırması beklenir?
new_cust = "fra_ios_female_31_40"
agg_df[agg_df["customers_level_based"] == new_cust]

,COUNTRY,SOURCE,SEX,AGE,PRICE,age_cat,customers_level_based,SEGMENT
208,fra,ios,female,40,33.000000,31_40,fra_ios_female_31_40,C
221,fra,ios,female,31,32.636364,31_40,fra_ios_female_31_40,C